name: ğŸ“± Mobile Update
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

jobs:
  eas-update:
    name: ğŸ“± EAS update
    runs-on: ubuntu-latest
    steps:
      - name: Set branch_name environment variable
        run: |
          REPO=${{github.ref}}
          BRANCH_NAME="${REPO/'refs/heads/'/''}"
          BRANCH_NAME="${BRANCH_NAME////-}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
      - name: ğŸ”Œ Checkout
        uses: actions/checkout@v3
      - name: ğŸ— Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: ğŸ“± Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: ğŸ’¾ Restore Turbo
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/turbo
          restore-keys: ${{ runner.os }}-turbo-
          key: |
            ${{ runner.os }}-turbo-${{ hashFiles('**/yarn.lock') }}
      - name: ğŸ’¾ Restore Metro
        uses: actions/cache@v3
        id: metro-cache
        with:
          path: |
            apps/chaban-mobile/metro-cache
            apps/chaban-mobile/.expo
            apps/chaban-mobile/dist
          restore-keys: ${{ runner.os }}-metro-
          key: |
            ${{ runner.os }}-metro-${{ hashFiles('**/yarn.lock') }}
      - name: â³ Yarn install
        run: yarn
      - name: ğŸš€ EAS Update production
        if: ${{ env.branch_name == 'main' }}
        working-directory: apps/chaban-mobile
        run: API_URL="${{secrets.API_URL}}" CHABAN_CHANNEL_ID="${{secrets.CHABAN_CHANNEL_ID}}"  eas update --branch main --message "Nouvelle version"
      - name: ğŸš€ EAS Update Peview
        if: ${{ env.branch_name != 'main' }}
        working-directory: apps/chaban-mobile
        run: API_URL="${{secrets.API_URL}}" CHABAN_CHANNEL_ID="${{secrets.CHABAN_CHANNEL_ID}}" eas update --branch pr-${{ github.event.number }} --message "Push update branch"
